# Generated by Django 5.1.2 on 2024-11-20 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='usu_nome', max_length=255)),
                ('email', models.EmailField(db_column='usu_email', max_length=255)),
            ],
            options={
                'db_table': 'tbl_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('tar_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tar_descricao', max_length=255)),
                ('setor', models.CharField(db_column='tar_setor', max_length=100)),
                ('prioridade', models.CharField(db_column='tar_prioridade', max_length=20)),
                ('status', models.CharField(db_column='tar_status', max_length=20)),
                ('data', models.DateField(db_column='tar_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(db_column='usu_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='website.usuario')),
            ],
            options={
                'db_table': 'tbl_tarefas',
            },
        ),
    ]
