# Generated by Django 5.1.7 on 2025-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
