# Generated by Django 5.1.5 on 2025-02-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('edicao', models.CharField(blank=True, max_length=45, null=True)),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('livro', models.ForeignKey(blank=True, db_column='livro', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.livros')),
            ],
            options={
                'db_table': 'estoque',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('data_compra', models.DateTimeField(blank=True, null=True)),
                ('livro_comprado', models.ForeignKey(blank=True, db_column='livro_comprado', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.livros')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('livro_vendido', models.ForeignKey(blank=True, db_column='livro_vendido', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.livros')),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='LivrosAutores',
            fields=[
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.livros')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.autores')),
            ],
            options={
                'db_table': 'livros_autores',
                'unique_together': {('livro', 'autor')},
            },
        ),
    ]
