# Generated by Django 5.1.5 on 2025-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
