# Generated by Django 5.1.5 on 2025-02-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='livro_comprado',
            field=models.ForeignKey(blank=True, db_column='livro_comprado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='website.livros'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='livro_vendido',
            field=models.ForeignKey(blank=True, db_column='livro_vendido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='website.livros'),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
