# Generated by Django 5.1.5 on 2025-02-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_tbltarefas_tar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltarefas',
            name='tar_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
