# Generated by Django 5.1.5 on 2025-01-29 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('lab_codigo', models.AutoField(db_column='lab_codigo', primary_key=True, serialize=False)),
                ('lab_nome', models.CharField(db_column='lab_nome', max_length=255)),
                ('lab_descricao', models.TextField(db_column='lab_descricao')),
                ('lab_capacidade', models.IntegerField(db_column='lab_capacidade')),
                ('lab_status', models.CharField(db_column='lab_status', max_length=45)),
            ],
            options={
                'db_table': 'tbl_laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_codigo', models.AutoField(db_column='usu_codigo', primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(db_column='usu_nome', max_length=255)),
                ('usu_email', models.EmailField(db_column='usu_email', max_length=255)),
                ('usu_cpf', models.CharField(db_column='usu_cpf', max_length=14)),
                ('usu_telefone', models.CharField(db_column='usu_telefone', max_length=11)),
                ('usu_tipoUsuario', models.CharField(db_column='usu_tipoUsuario', max_length=13)),
                ('usu_senha', models.CharField(db_column='usu_senha', max_length=45)),
            ],
            options={
                'db_table': 'tbl_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Horario_reserva',
            fields=[
                ('hor_codigo', models.AutoField(db_column='hor_codigo', primary_key=True, serialize=False)),
                ('hor_inicio', models.DateTimeField(db_column='hor_inicio')),
                ('hor_fim', models.DateTimeField(db_column='hor_fim')),
                ('hor_diasDisponiveis', models.DateField(db_column='hor_diasDisponiveis')),
                ('laboratorio', models.ForeignKey(db_column='lab_codigo_hor', on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_horario_reserva', to='website.laboratorios')),
            ],
            options={
                'db_table': 'tbl_horario_reserva',
            },
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('equip_codigo', models.AutoField(db_column='equip_codigo', primary_key=True, serialize=False)),
                ('equip_nome', models.CharField(db_column='equip_nome', max_length=30)),
                ('equip_descricao', models.TextField(db_column='equip_descricao')),
                ('laboratorio', models.ForeignKey(db_column='lab_codigo_equip', on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_equipamentos', to='website.laboratorios')),
            ],
            options={
                'db_table': 'tbl_equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('res_codigo', models.AutoField(db_column='res_codigo', primary_key=True, serialize=False)),
                ('res_inicio', models.DateTimeField(db_column='res_inicio')),
                ('res_fim', models.DateTimeField(db_column='res_fim')),
                ('res_repeticao', models.BooleanField(db_column='res_repeticao', db_default=False)),
                ('res_status', models.CharField(db_column='res_status', max_length=45)),
                ('laboratorio', models.ForeignKey(db_column='lab_codigo_res', on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_reservas', to='website.laboratorios')),
                ('usuario', models.ForeignKey(db_column='usu_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='website.usuarios')),
            ],
            options={
                'db_table': 'tbl_reservas',
            },
        ),
    ]
