# Generated by Django 5.1.7 on 2025-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
