# Generated by Django 5.1.5 on 2025-03-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
