# Generated by Django 5.1.7 on 2025-04-28 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_escola_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='horario_funcionamento',
        ),
        migrations.AddField(
            model_name='escola',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, default='sem_foto.jpeg', null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
