# Generated by Django 5.1.7 on 2025-04-29 13:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_escola_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReservas',
            fields=[
                ('res_codigo', models.IntegerField(blank=True, db_column='res_codigo', db_index=True)),
                ('res_inicio', models.DateTimeField(db_column='res_inicio')),
                ('res_fim', models.DateTimeField(db_column='res_fim')),
                ('res_repeticao', models.CharField(choices=[('N', 'Não repetir'), ('D', 'Diariamente'), ('S', 'Semanalmente'), ('M', 'Mensalmente'), ('A', 'Anualmente')], db_column='res_repeticao', default='N', max_length=1)),
                ('res_status', models.CharField(db_column='res_status', max_length=45)),
                ('res_intervalo_semanas', models.PositiveIntegerField(blank=True, db_column='res_intervalo_semanas', null=True)),
                ('res_dia_semana', models.JSONField(blank=True, db_column='res_dia_semana', null=True)),
                ('res_data_final_repeticao', models.DateField(blank=True, db_column='res_data_final_repeticao', null=True)),
                ('res_descricao', models.TextField(blank=True, db_column='res_descricao')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(blank=True, db_column='lab_codigo_res', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='website.laboratorios')),
                ('professor', models.ForeignKey(blank=True, db_column='professor_codigo_reserva', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reservas',
                'verbose_name_plural': 'historical reservass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
