# Generated by Django 5.1.5 on 2025-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_escola_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usu_senha',
            field=models.CharField(db_column='usu_senha', max_length=100),
        ),
    ]
