# Generated by Django 5.1.7 on 2025-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_usuarios_usu_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usu_cpf',
            field=models.CharField(db_column='usu_cpf', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usu_senha',
            field=models.CharField(db_column='usu_senha', max_length=50),
        ),
    ]
