# Generated by Django 5.1.7 on 2025-04-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_historicalreservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservas',
            name='res_repeticao_original',
            field=models.ForeignKey(blank=True, db_column='res_repeticao_original', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='website.reservas'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='res_repeticao_original',
            field=models.ForeignKey(blank=True, db_column='res_repeticao_original', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeticoes', to='website.reservas'),
        ),
    ]
