# Generated by Django 5.1.7 on 2025-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_usuarios_usu_cpf_alter_usuarios_usu_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usu_senha',
            field=models.CharField(db_column='usu_senha', max_length=255),
        ),
    ]
