# Generated by Django 5.1.7 on 2025-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_usuarios_usu_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usu_telefone',
            field=models.CharField(db_column='usu_telefone', max_length=14),
        ),
    ]
