# Generated by Django 5.1.5 on 2025-02-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('usu_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_usuario',
            },
        ),
        migrations.CreateModel(
            name='TblTarefas',
            fields=[
                ('tar_id', models.AutoField(primary_key=True, serialize=False)),
                ('tar_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tar_nomesetor', models.CharField(blank=True, db_column='tar_nomeSetor', max_length=60, null=True)),
                ('tar_prioridade', models.CharField(blank=True, max_length=20, null=True)),
                ('tar_data', models.DateField(blank=True, null=True)),
                ('tar_status', models.CharField(blank=True, max_length=20, null=True)),
                ('usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.tblusuario')),
            ],
            options={
                'db_table': 'tbl_tarefas',
            },
        ),
    ]
