# Generated by Django 5.1.5 on 2025-02-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltarefas',
            name='tar_status',
            field=models.CharField(blank=True, default='A fazer', max_length=20, null=True),
        ),
    ]
