# Generated by Django 5.1.7 on 2025-05-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_setor', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridade', models.CharField(blank=True, max_length=45, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('usuarios', models.ForeignKey(db_column='Usuarios_id', on_delete=django.db.models.deletion.CASCADE, to='website.usuarios')),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
