# Generated by Django 5.1.7 on 2025-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(blank=True, default='A fazer', max_length=45, null=True),
        ),
    ]
